services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kvantino
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - "./postgres/data:/var/lib/postgresql/data"
    ports:
      - 5438:5432
    networks:
      - bn-net
    restart: unless-stopped

  bn-app:
    image: 'book-network'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    networks:
      - bn-net
    container_name: book-network-app
    depends_on:
      - postgres
      - mail-dev
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/book_social_network
#      - SPRING_DATASOURCE_USERNAME= postgres
#      - SPRING_DATASOURCE_PASSWORD= kvantino
      - SPRING_MAIL_HOST=mail-dev
      - SPRING_MAIL_PORT=1025
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  bn-ui:
    build:
      context: ./book-network-ui
    container_name: book-network-ui
    ports:
      - 4200:80
    depends_on:
      - bn-app

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - bn-net

networks:
  bn-net:
    driver: bridge

#volumes:
#  postgres:
#    driver: local



