create table users(
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(50) not null ,
    last_name varchar(50) not null ,
    phone_number varchar(30) ,
    email varchar(50) not null ,
    password varchar(255) ,
    user_role varchar(50)
)