services:
  postgres:
    container_name: postgres-sql-gc
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kvantino
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: gizmo_chat_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - gizmo-chat
    restart: unless-stopped

  keycloak:
    container_name: keycloak-gc
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - gizmo-chat
    command:
      - "start-dev"

networks:
  gizmo-chat:
    driver: bridge

volumes:
  postgres:
    driver: local
