create table server
(
    id         bigint primary key generated by default as identity,
    ip_address varchar(30) unique not null,
    name       varchar(50),
    memory     varchar(10),
    type       varchar(50),
    image_url  varchar(255),
    status     integer
);

insert into server(ip_address, name, memory, type, image_url, status)
VALUES ('192.168.1.160', 'Ubuntu Linux', '16 GB', 'Personal PC', 'http://localhost:8080/server/image/server1.png', 0);

insert into server(ip_address, name, memory, type, image_url, status)
VALUES ('192.168.1.34', 'Fedora Linux', '16 GB', 'Dell Tower', 'http://localhost:8080/server/image/server2.png', 0);

insert into server(ip_address, name, memory, type, image_url, status)
VALUES ('192.168.1.23', 'MS Server 2012', '32 GB', 'Web Server', 'http://localhost:8080/server/image/server3.png', 0);

insert into server(ip_address, name, memory, type, image_url, status)
VALUES ('192.168.1.167', 'Cent OS', '8 GB', 'Network Monitor', 'http://localhost:8080/server/image/server4.png', 0);

insert into server(ip_address, name, memory, type, image_url, status)
VALUES ('192.168.1.88', 'MS Windows 10', '8 GB', 'Personal PC', 'http://localhost:8080/server/image/server1.png', 1);

