spring:
  application:
    name: book-network-api
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: kvantino
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    open-in-view: true
  #    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: nikola
    password: kvantino
    properties:
      smtp:
        trust: "*"
      auth: true
      starttls:
        enable: true
      connectiontimeout: 5000
      timeout: 3000
      writetimeout: 5000

application:
  security:
    jwt:
      secret-key: M@rg@lK0chJg1rK0ch
      expiration: 8640000

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
server:
  port: 8088
