spring:
  application:
    name: book-network-api
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: kvantino
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    open-in-view: true
  #    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: nikola
    password: kvantino
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 5f2a667ebaa2673578aaf843d268d82ac59941c4fa9368691e3532a8905f5d9b
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # a week

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088
